language: go

go:
  - 1.3
  - 1.4
  - tip

before_install:
  - go get github.com/ogier/pflag
  - go get golang.org/x/tools/cmd/vet
  - go get github.com/golang/lint/golint
  - sudo apt-get update
  - sudo apt-get install vim-common

script:
  - go vet -x
  - golint
  - go test -v -xxdFile=image.jpg -sysXxd=xxd